### ISSUE TITLE
GetLastRxTimestamp() always returs 0

### ISSUE THREAD

**Issue by royh99** [jsphuebner/libopeninv#14]
GetLastRxTimestamp() in canhardware.h always returns 0 as lastRxTimestamp is never changed from the initial value.

**Comment by jsphuebner** [comment]
It is updated here: https://github.com/jsphuebner/libopeninv/blob/master/src/stm32_can.cpp#L218

It's debatable whether this should happen in the hardware backend though but rather in the higher level canhardware.cpp
