### ISSUE TITLE
Mapping of a 16 bit signal to CAN leads to data loss in certain cases

### ISSUE THREAD

**Issue by uhi22** [jsphuebner/libopeninv#17]
I have a spot value with 16 bits, which contains the value 710 = 0x02C6. When mapping this to CAN messages, the result is different depending on which position it is mapped. The error happens if the 16 bit value is mapped to bit 24, then the high-byte is lost.
![image](https://github.com/jsphuebner/libopeninv/assets/98478946/a4eb0d38-c7cc-4e06-b52d-012b02ff0fe9)
This is the related configuration:
![image](https://github.com/jsphuebner/libopeninv/assets/98478946/6f151e6f-7b0f-4765-8ba2-e02791e5f2fc)

I did not check all possible combination, so the error may or may not be present for other positions or data sizes, too.

**Comment by jsphuebner** [comment]
Yes this is a known limitation of the mapping module https://openinverter.org/wiki/CAN_communication#Limits
Data is processed in two 32-bit words and cannot span across them.
Lets keep the issue open anyway because it could be worth fixing

**Comment by jsphuebner** [comment]
Fixed in 297639d676ab5325936b6ff418aca55be425195c
