### ISSUE TITLE
void CanHardware::HandleRx - more then one use of ID causes issues

### ISSUE THREAD

**Issue by Tom-evnut** [jsphuebner/libopeninv#20]
When the main code and the CAN map both share ids it wont be sent to both.

Fix:
```
void CanHardware::HandleRx(uint32_t canId, uint32_t data[2], uint8_t dlc)
{
   for (int i = 0; i < nextCallbackIndex; i++)
   {
      if (recvCallback[i]->HandleRx(canId, data, dlc))
      {
         //break;
      }
   }
}
```

Verified working on STM32_VCU Zombie. This allows populating of info like HV bus measurement from devices already used.

**Comment by jamiejones85** [comment]
Just to add meat to the bones, the issue is that if you add an RX map for an ID and the code also uses that ID, the handlers down the list will never receive it.

**Comment by jsphuebner** [comment]
That is intended but I see the problem. You could register the other handlers before CanMap and return false in them

**Comment by davefiddes** [comment]
That is an odd design choice IMO. It runs counter to the publish-subscribe pattern of CAN messaging. If a CanHardware user has expressed an interest in a particular ID shouldn't it just get an opportunity to process it.

Why does it work that way?

**Comment by jsphuebner** [comment]
All handlers are called on all ids.That is way easier to implement rather than remembering which handler is interested in which ID. So I thought this would prevent unnecessary handler calls. But I see the downsides are more severe. Feel free to remove it (and the return value of HandleRx)

**Comment by davefiddes** [comment]
I've raised a PR that addresses your problem @Tom-evnut and @jamiejones85. Any chance you could test with the problem you were seeing? I don't have VCU hardware and environment to test currently. Thanks.
