### ISSUE TITLE
CanMap::Remove() leaks canPosMap entries each time it is used eventually stopping CanMap::AddSend()/Recv() from working

### ISSUE THREAD

**Issue by davefiddes** [jsphuebner/libopeninv#24]
Reported by a number of [OI users](https://openinverter.org/forum/viewtopic.php?p=75917#p75917). CAN parameter mapping can stop working after a while when modifying maps.

To replicate:
 - Take stm32-sine with current libopeninv tip
 - Clear the CAN map with `can c` and then `save`
 - Use openinverter CAN tool with the attached CAN map
[oic-map-test-new-2.json](https://github.com/user-attachments/files/17464866/oic-map-test-new-2.json) and run `oic can import oic-map-test-new-2.json`
- Run the command 4 times

Expected result:
 - The tool displays the following output each time it is run:
```text
$ oic can import oic-map-test-new-2.json 
Existing CAN message map cleared
Transmit CAN message map configured
Receive CAN message map configured
```

Actual result:
 - On the 4th invocation the mapping fails:
```text
$ oic can import ../oic-map-test-new-2.json 
Existing CAN message map cleared
Command or parameter not supported
```
 - Further attempts to add CAN map entries fail
 - If the CAN map is saved it the error condition will persist

**Comment by jsphuebner** [comment]
Thanks for the fault finding so far. I take it the error is in the code for Remove()? Or Add()?

**Comment by davefiddes** [comment]
I don't really understand how it's supposed to work. The problem seems to be that Remove() doesn't mark canPosMap entries as unallocated as it shuffles things up in the linked list.

**Comment by jsphuebner** [comment]
I believe it is fixed. Indeed I had just forgotten to mark deleted mapping as unused. Also added more comments so it becomes clearer

**Comment by davefiddes** [comment]
That seems to fix it. Threw a collection of random CAN maps at a device in a loop with oic for about 30 minutes and it was solid. Not the be all and end all of testing but it seems solid.

**Comment by jsphuebner** [comment]
Nice, thanks!
